seed: 42

architecture:
  name: llpr
  training:
    model_checkpoint: model.ckpt
    batch_size: 1

training_set:
  systems:
    read_from: dataset.xyz
    length_unit: angstrom
  targets:
    energy:
      key: energy
      unit: eV

validation_set: 0.1
test_set: 0.1
