seed: 42

architecture:
  name: pet
  training:
    batch_size: 10
    num_epochs: 1000

training_set:
  systems:
    read_from: dataset.xyz
    length_unit: angstrom
  targets:
    energy:
      key: energy
      unit: eV

validation_set: 0.1
test_set: 0.1
